### ISSUE TITLE
ESPHome 2025.2.2 does not accept custom components anymore

### ISSUE THREAD

**Issue by miketenwolde** [grapefrukt/esphome-optoma#2]
ESPHome 2025.2.2 does not accept custom components anymore, would you be so kind to replace your uart_read_line_sensor.h into an external component?

**Comment by grapefrukt** [comment]
I fixed this very issue in #1 just last week, you should be able to grab the new yaml and go (note that it's on the 2025.2 branch)

**Comment by grapefrukt** [comment]
Do let me know if you have any issues though!

**Comment by miketenwolde** [comment]
> Do let me know if you have any issues though!

Seems to be working perfectly, thank for the quick response!

I also implemented this:
```
button:
  - platform: template
    icon: mdi:air-filter
    name: "Filter reset"
    on_press:
      - uart.write: [0x7E, 0x30, 0x30, 0x33, 0x32, 0x33, 0x20, 0x31, 0x0D]
```
